### PR TITLE
Update details on ManiSkill/SAPIEN about new GPU parallelized sim + parallelized rendering

### PR DESCRIPTION
**Pull request by StoneT2000**
Added some updates.

Furthermore I have two questions about things to add (that are clearly biased towards my own work so I do not add them in this PR):
- I would like to add ManiSkill under the simulators list as most robot learning people will use that API as opposed to direct SAPIEN for GPU simulation / parallel rendering but it's not exactly at the physics/simulation engine of the tech stack (and I am obviously very biased here). 
- I would like to also add a category to the comparison table about parallel rendering as it is a mostly unique feature of ManiSkill/SAPIEN, and I believe [mjx also supports parallel depth-only rendering](https://github.com/google-deepmind/mujoco/issues/1485) via mjx.ray although I don't know if that is an official feature (and I haven't tried it myself yet).
I leave the two points above a decision to be made by the other maintainers.

Thanks!

### CODE REVIEW

**Comment by geng-haoran** [comment]
Thank you very much for the information!

**Comment by geng-haoran** [comment]
(1) Thank you for your valuable suggestions. I've also noticed that SAPIEN and ManiSkill have always been merged together, with the latest APIs often appearing with the release of a new ManiSkill. Do you think it's a good idea for us to combine them both? Like in the title, we name it SAPIEN&ManiSkill or something similar.
(2) It sounds great! Thank you very much for your suggestions and help. We already have a table for parallel rendering, but if you could add more information and make the table complete, that would be great!

**Comment by StoneT2000** [comment]
1) Sure I think this can be useful. The projects are built/maintained by the same group essentially, and IsaacGym has it's own section despite not being the low level simulation framework. (Actually IsaacGym is deprecated in favor of IsaacLab now). I can make a PR to refactor a bit later

2) Where is the table for parallel rendering section? I only found the details for FPS for a single environment

**Comment by geng-haoran** [comment]
(1) Thank you so much!
(2) Oh yes. [here](https://simulately.wiki/docs/comparison) we compared the rendering speed for a single env. Parallel rendering is also very very important feature and previous simulators can not achieve it well. People struggle it a lot. Thanks ManiSkill for the contribution and let's make a table for it!

**Pull request merged**
